from pgradd.GroupAdd.Library import GroupLibrary
import pgradd.ThermoChem
libGuA = GroupLibrary.Load('GuSolventGA2017Aq')
libGuV = GroupLibrary.Load('GuSolventGA2017Vac')
libGR = GroupLibrary.Load('GRWAqueous2018')
lib = GroupLibrary.Load('GRWSurface2018')
libS = GroupLibrary.Load('SalciccioliGA2012')
libX = GroupLibrary.Load('XieGA2022')
libB = GroupLibrary.Load('BensonGA')
#descriptors = lib.GetDescriptors('CCC(=O)N(C1CCN(CC1)CCc2ccccc2)c3ccccc3') it doesn't like this...
descriptors = libGuA.GetDescriptors('CCC(=O)C(C1CCC(CC1)CCc2ccccc2)c3ccccc3')
print(descriptors)
descriptors = libGuV.GetDescriptors('CCC(=O)C(C1CCC(CC1)CCc2ccccc2)c3ccccc3')
print(descriptors)
descriptors = libGR.GetDescriptors('CCC(=O)C(C1CCC(CC1)CCc2ccccc2)c3ccccc3')
print(descriptors)
descriptors = libS.GetDescriptors('CCC(=O)C(C1CCC(CC1)CCc2ccccc2)c3ccccc3')
print(descriptors)
descriptors = libX.GetDescriptors('CCC(=O)C(C1CCC(CC1)CCc2ccccc2)c3ccccc3')
print(descriptors)
descriptors = libB.GetDescriptors('CCC(=O)C(C1CCC(CC1)CCc2ccccc2)c3ccccc3')
print(descriptors)
descriptors = lib.GetDescriptors('CCC(=O)C(C1CCC(CC1)CCc2ccccc2)c3ccccc3')
print(descriptors)
thermochem = libB.Estimate(descriptors,'thermochem')
print((thermochem.get_HoRT(298)))